name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    # timeout-minutes: 55
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Random interval control
      id: random
      run: |
        RAND=$(( RANDOM % 3 ))
        if [ "$RAND" -eq 0 ]; then
          echo "run_job=false" >> $GITHUB_OUTPUT
        else
          echo "run_job=true" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies
      if: steps.random.outputs.run_job == 'true'
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update

        sudo apt-get install -y libgbm-dev  # Required for Playwright in multiprocessing

        pip install -r requirements.txt

    - name: Install Playwright
      if: steps.random.outputs.run_job == 'true'
      run: |
        playwright install --with-deps chromium

    - name: Create Firebase Credentials
      if: steps.random.outputs.run_job == 'true'
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        echo "$FIREBASE_CREDENTIALS" > service-account.json
        echo "Firebase credentials created"

    - name: Create LinkedIn Session State
      if: steps.random.outputs.run_job == 'true'
      env:
        LINKEDIN_SESSION: ${{ secrets.LINKEDIN_SESSION_STATE }}
      run: |
        echo "$LINKEDIN_SESSION" > state_main.json
        echo "LinkedIn session state created"
    - name: Set LinkedIn Credentials
      if: steps.random.outputs.run_job == 'true'
      env:
        LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
      run: echo "LinkedIn credentials loaded"

    - name: Run scraper
      if: steps.random.outputs.run_job == 'true'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: |
        python main.py

    - name: Commit updated session state
      if: steps.random.outputs.run_job == 'true' && success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull origin main
        git add state.json
        git commit -m "🔄 Update LinkedIn session state"
        git push origin main