name: LinkedIn Job Scraper
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes for testing
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin playwright pytz requests beautifulsoup4

    - name: Install Playwright browsers
      uses: microsoft/playwright-github-action@v1.8.0
      with:
        browsers: chromium

    - name: Validate and Create Firebase Credentials
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        echo "$FIREBASE_CREDENTIALS" | python -c "
import json, sys, os;
try:
    creds = json.loads(os.environ['FIREBASE_CREDENTIALS']);
    with open('firebase-key.json', 'w') as f:
        json.dump(creds, f, indent=2);
    print('Firebase credentials file created successfully.');
except Exception as e:
    print(f'Error creating firebase-key.json: {e}');
    sys.exit(1);"
        cat firebase-key.json

    - name: Run scraper
      run: |
        python main.py
