name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '30 */1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04  # Critical: Use supported LTS version
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Random interval control
      id: random
      run: |
        # Generate random number (0, 1)
        # Adjust probabilities by changing the modulus and conditions
        RAND=$(( RANDOM % 3 ))
        if [ "$RAND" -eq 0 ]; then
          echo "Skipping to next slot (45m interval)"
          echo "run_job=false" >> $GITHUB_OUTPUT
        else
          echo "Proceeding (90m interval)"
          echo "run_job=true" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies
      if: steps.random.outputs.run_job == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright
      if: steps.random.outputs.run_job == 'true'
      run: |
        playwright install --with-deps chromium
        playwright install chromium
    - name: Create Firebase Credentials
      if: steps.random.outputs.run_job == 'true'

      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        # Write credentials with proper JSON formatting
        python -c "import os,json; open('firebase-key.json','w').write(os.environ['FIREBASE_CREDENTIALS'])"
        
        # Verify credentials
        echo "Firebase credentials validation:"
        python -c "import json; json.load(open('firebase-key.json'))"
        echo -e "\nFile structure:"
        ls -la firebase-key.json
    - name: Run scraper
      if: steps.random.outputs.run_job == 'true'
      run: |
        python main.py