name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04  # Critical: Use supported LTS version
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright
      run: |
        playwright install --with-deps chromium
        playwright install chromium
    - name: Create Firebase Credentials
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        # Write credentials with proper JSON formatting
        python -c "import os,json; open('firebase-key.json','w').write(os.environ['FIREBASE_CREDENTIALS'])"
        
        # Verify credentials
        echo "Firebase credentials validation:"
        python -c "import json; json.load(open('firebase-key.json'))"
        echo -e "\nFile structure:"
        ls -la firebase-key.json

    - name: Debug Firebase Creds
      run: |
        echo "Credentials content:"
        cat firebase-key.json
        echo -e "\nFile size: $(wc -c < firebase-key.json)"

    # - name: Create Firebase Credentials
    #   env:
    #     FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    #   run: |
    #     echo "$FIREBASE_CREDENTIALS" > firebase-key.json

    - name: Run scraper
      run: |
        python main.py